# Generated by Django 2.1.4 on 2018-12-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('pm25', models.IntegerField()),
                ('nco', models.IntegerField()),
                ('nso2', models.IntegerField()),
                ('no3', models.IntegerField()),
                ('nnh3', models.IntegerField()),
                ('nno2', models.IntegerField()),
            ],
        ),
    ]
