# Generated by Django 2.1.4 on 2019-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pm1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
