# Generated by Django 2.1.4 on 2019-02-07 13:47

from django.db import migrations
import sensors.models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nco',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=1000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nnh3',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=1000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nno2',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=1000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='no3',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=1000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='nso2',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=1000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pm1',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=500),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pm10',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=500),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pm25',
            field=sensors.models.SensorIntegerField(low_limit=0, up_limit=500),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pressure',
            field=sensors.models.SensorIntegerField(low_limit=900000, up_limit=1200000),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=sensors.models.SensorIntegerField(low_limit=-6000, up_limit=6000),
        ),
    ]
